version: '3.8'

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    environment:
      REDIS_HOST: redis
    networks:
      - poll-tier
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: unless-stopped

  worker:
    build: ./worker
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - result-tier
      - back-tier
    restart: unless-stopped

  result:
    build: ./result
    ports:
      - "5001:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - result-tier
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier: